from __future__ import annotations

"""
MatchStore — cross-platform deduplication store.

Maintains an append-only JSONL file that maps a normalized match key
(derived from street address, or a postcode+rooms+price bucket when no
address is available) to the first Listing seen at that location.

When a later adapter returns a listing whose key is already in the store,
the pipeline skips the email and instead appends the duplicate URL to the
Google Sheet row already created for the original notification.
"""

import json
import logging
import os
import re

from .adapters.base import Listing

log = logging.getLogger(__name__)


def _normalize_address(address: str) -> str:
    """Lowercase, strip all punctuation/special chars, collapse whitespace."""
    s = address.lower()
    s = re.sub(r"[^\w\s]", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _extract_street_number(address: str) -> str:
    """Return normalized street + house number, stripping the Swiss postcode and city.

    Takes everything before the first 4-digit postcode token.  If no postcode is
    found (e.g. Comparis omits it), the full address is used as-is.  Result is
    always run through ``_normalize_address``.

    Examples:
        "Musterstrasse 12, 8006 Zürich" → "musterstrasse 12"
        "Musterstrasse 12"              → "musterstrasse 12"   (same key)
    """
    m = re.search(r"\b\d{4}\b", address)
    if m:
        before = address[: m.start()].strip().strip(",").strip()
        if before:
            return _normalize_address(before)
    return _normalize_address(address)


def _is_real_street_address(address: str) -> bool:
    """Return True only when the address contains a street name *and* a house number.

    A bare ``"<postcode> <city>"`` string such as ``"8044 Zürich"`` returns False
    and must not be used for address-based dedup — it would cause two different
    flats in the same postcode to collide.

    Strategy: strip the 4-digit Swiss postcode token, then require the remainder
    to contain both letter characters (street name) and at least one digit (house
    number).  This catches strings like ``"Bahnhofstrasse 1, 8001 Zürich"`` or
    ``"Hauptstrasse 12a, 8044 Zürich"`` but rejects ``"8044 Zürich"`` (no letters
    after postcode removal) and ``"Bahnhofstrasse, 8001 Zürich"`` (no digit after
    postcode removal).
    """
    without_postcode = re.sub(r"\b\d{4}\b", "", address)
    has_letters = bool(re.search(r"[^\W\d_]", without_postcode, re.UNICODE))
    has_house_number = bool(re.search(r"\d", without_postcode))
    return has_letters and has_house_number


class MatchRecord:
    __slots__ = ("uid", "url", "sheet_row")

    def __init__(self, uid: str, url: str, sheet_row: int | None) -> None:
        self.uid = uid
        self.url = url
        self.sheet_row = sheet_row


class MatchStore:
    """
    Cross-platform deduplication store (JSONL, append-only, crash-safe).

    One instance is shared across the full run_cycle call so that a listing
    found on Flatfox is remembered when Homegate returns the same apartment
    in the same cycle.

    Each listing may have multiple dedup keys generated by ``match_keys``.  All
    applicable keys are stored when a listing is first registered, and all are
    tried in order when checking for duplicates (``lookup_any``).  The key types
    and their priority order:

    1. ``"addr:<normalised address>"``  — real street address (street + house
       number).  Most precise; checked first.  A bare ``"<postcode> <city>"``
       does NOT qualify; ``_is_real_street_address`` gates this.

    2. ``"street:<normalised street+number>"``  — same as ``addr:`` but with the
       Swiss postcode and city stripped out.  Enables cross-platform dedup when
       one adapter (e.g. Comparis) returns only ``"Musterstrasse 12"`` while
       another returns the full ``"Musterstrasse 12, 8006 Zürich"``.  Both
       normalise to the same ``street:musterstrasse 12`` key.  Only generated
       when the address contains a real street+number (same gate as ``addr:``).

    3. ``"title:<normalised title>|<postcode>|<rooms>"``  — present whenever
       title and postcode are known.  Catches cross-platform duplicates where
       one adapter has a full address and another only has ``<postcode> <city>``.
       Rooms prevents generic-title false positives.  Price is excluded so that
       a ``price_on_request`` listing still deduplicates against the priced entry
       on another platform.

    4. ``"bucket:<postcode>|<rooms>|<price_bucket>"``  — last resort when no real
       street address and no title are available, but postcode + rooms + price
       are known.  price_bucket = round(price_chf / 50) (CHF 50 granularity).

    Because all keys are stored and checked, two listings with the same address
    but different titles (e.g. one in German, one in English) still deduplicate
    via the ``addr:`` key — the title-based key is an *additional* signal, not a
    replacement for address matching.
    """

    def __init__(self, path: str) -> None:
        self._path = path
        self._records: dict[str, MatchRecord] = {}
        self._load()

    # ── private ──────────────────────────────────────────────────────────────

    def _load(self) -> None:
        if not os.path.exists(self._path):
            log.info("action=matchstore_init path=%s", self._path)
            return
        with open(self._path) as f:
            for raw in f:
                line = raw.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                    key = entry["key"]
                    self._records[key] = MatchRecord(
                        uid=entry["uid"],
                        url=entry["url"],
                        sheet_row=entry.get("sheet_row"),
                    )
                except (KeyError, json.JSONDecodeError):
                    log.warning("action=matchstore_bad_line line=%r", line[:80])
        log.info(
            "action=matchstore_loaded count=%d path=%s",
            len(self._records),
            self._path,
        )

    # ── public API ────────────────────────────────────────────────────────────

    def match_keys(self, listing: Listing) -> list[str]:
        """Return all applicable dedup keys for a listing, in priority order.

        Every returned key is stored on write and checked on lookup.  Using all
        keys ensures that two listings for the same flat always match even when
        one platform has a full street address, another has only postcode+city,
        or one (e.g. Comparis) has street+number without a postcode.
        """
        keys: list[str] = []
        if listing.address and _is_real_street_address(listing.address):
            keys.append("addr:" + _normalize_address(listing.address))
            keys.append("street:" + _extract_street_number(listing.address))
        if listing.title and listing.postcode:
            rooms_str = str(listing.rooms) if listing.rooms is not None else "x"
            keys.append(
                "title:"
                + _normalize_address(listing.title)
                + "|"
                + listing.postcode
                + "|"
                + rooms_str
            )
        if (
            listing.postcode
            and listing.rooms is not None
            and listing.price_chf is not None
        ):
            bucket = round(listing.price_chf / 50)
            keys.append(f"bucket:{listing.postcode}|{listing.rooms}|{bucket}")
        return keys

    def match_key(self, listing: Listing) -> str | None:
        """Return the primary (most specific) dedup key, or None.

        Convenience wrapper over ``match_keys``; returns the first key or None.
        Use ``lookup_any`` and store under ``match_keys`` in production code.
        """
        keys = self.match_keys(listing)
        return keys[0] if keys else None

    def lookup_any(self, listing: Listing) -> MatchRecord | None:
        """Return the first stored record that matches any of the listing's keys."""
        for key in self.match_keys(listing):
            rec = self._records.get(key)
            if rec is not None:
                return rec
        return None

    def lookup(self, key: str) -> MatchRecord | None:
        """Return the stored record for *key*, or None."""
        return self._records.get(key)

    def add(
        self,
        key: str,
        uid: str,
        url: str,
        sheet_row: int | None = None,
    ) -> None:
        """Persist a new match record (in memory + appended to JSONL file)."""
        record = MatchRecord(uid=uid, url=url, sheet_row=sheet_row)
        self._records[key] = record
        entry = {"key": key, "uid": uid, "url": url, "sheet_row": sheet_row}
        with open(self._path, "a") as f:
            f.write(json.dumps(entry) + "\n")
        log.info("action=matchstore_added key=%s uid=%s", key, uid)
